name: portfolio
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/done/
    - assets/green_screen_studio/
    - assets/rated/
    - assets/russeknutene/
    - assets/slurk/
    - assets/i_am/
    - assets/time_to_death/
